apiVersion: extensions/v1beta3
kind: Deployment
metadata:
  name: jaeger-flask
  labels:
    app: jaeger-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-flask
  template:
    metadata: 
      labels:
        app: jaeger-flask
    spec:
     containers:
     - image: pravarag/jaeger-trace-python:updated_image
       name: jaeger-flask-main-image
       ports:
        containerPort: 8081