apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-tracer-app1
  labels:
    app: jaeger-tracer-app1
spec:
  replicas: {{ .Values.app1.replicaCount  }}
  selector:
    matchLabels:
      app: jaeger-tracer-app1
  template:
    metadata: 
      labels:
        app: jaeger-tracer-app1
    spec:
     containers:
     - image: {{ .Values.app1.image.repository }}:{{ .Values.app1.image.tag  }}
       name: jaeger-tracer-app1
       ports:
       - containerPort: {{ .Values.app1.image.port }}
       env: 
       - name: JAEGER_AGENT_HOST
         value: {{ .Values.jaegerAgentHost }}
       - name: IP
         value: app2-service.default.svc.cluster.local
       - name: REDIS_HOST
         value: redis-service.default.svc.cluster.local