apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-tracer-app1
  labels:
    app: jaeger-tracer-app1
spec:
  replicas: {{ .Values.app1.replicaCount  }}
  selector:
    matchLabels:
      app: jaeger-tracer-app1
  template:
    metadata: 
      labels:
        app: jaeger-tracer-app1
    spec:
     containers:
     - image: {{ .Values.app1.image.repository }}:{{ .Values.app1.image.tag  }}
       name: jaeger-tracer-app1
       ports:
       - containerPort: {{ .Values.app1.image.port }}
