apiVersion: v1
kind: Service
metadata:
  name: app1-service
  labels:
    app: app1
spec:
  ports:
  - name: app1-service
    port: {{ .Values.app1.image.port }}
    targetPort: {{ .Values.app1.image.targetPort }}
  selector:
    app: app1
