apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-tracer-app2
  labels:
    app: jaeger-tracer-app2
spec:
  replicas: {{ .Values.app2.replicaCount }}
  selector:
    matchLabels:
      app: jaeger-tracer-app2
  template:
    metadata: 
      labels:
        app: jaeger-tracer-app2
    spec:
     containers:
     - image: {{ .Values.app2.image.repository }}:{{ .Values.app2.image.tag }}
       name: jaeger-tracer-app2-image
       ports:
       - containerPort: {{ .Values.app2.image.port }}
